//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purge.AkamaiPurgeCache {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.akamai.com/purge", ConfigurationName="AkamaiPurgeCache.PurgeApi")]
    public interface PurgeApi {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Purge.AkamaiPurgeCache.PurgeResult purgeRequest(string name, string pwd, string network, string[] opt, string[] uri);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1009")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.akamai.com/purge")]
    public partial class PurgeResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int resultCodeField;
        
        private string resultMsgField;
        
        private string sessionIDField;
        
        private int estTimeField;
        
        private int uriIndexField;
        
        private string[] modifiersField;
        
        /// <remarks/>
        public int resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
                this.RaisePropertyChanged("resultCode");
            }
        }
        
        /// <remarks/>
        public string resultMsg {
            get {
                return this.resultMsgField;
            }
            set {
                this.resultMsgField = value;
                this.RaisePropertyChanged("resultMsg");
            }
        }
        
        /// <remarks/>
        public string sessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
                this.RaisePropertyChanged("sessionID");
            }
        }
        
        /// <remarks/>
        public int estTime {
            get {
                return this.estTimeField;
            }
            set {
                this.estTimeField = value;
                this.RaisePropertyChanged("estTime");
            }
        }
        
        /// <remarks/>
        public int uriIndex {
            get {
                return this.uriIndexField;
            }
            set {
                this.uriIndexField = value;
                this.RaisePropertyChanged("uriIndex");
            }
        }
        
        /// <remarks/>
        public string[] modifiers {
            get {
                return this.modifiersField;
            }
            set {
                this.modifiersField = value;
                this.RaisePropertyChanged("modifiers");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PurgeApiChannel : Purge.AkamaiPurgeCache.PurgeApi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PurgeApiClient : System.ServiceModel.ClientBase<Purge.AkamaiPurgeCache.PurgeApi>, Purge.AkamaiPurgeCache.PurgeApi {
        
        public PurgeApiClient() {
        }
        
        public PurgeApiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PurgeApiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurgeApiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurgeApiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Purge.AkamaiPurgeCache.PurgeResult purgeRequest(string name, string pwd, string network, string[] opt, string[] uri) {
            return base.Channel.purgeRequest(name, pwd, network, opt, uri);
        }
    }
}
